//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public string Exam_Name { get; set; }
        public string Question_Text { get; set; }
        public double Question_Score { get; set; }
        public int Type { get; set; }
        public string mcq_Choice_1 { get; set; }
        public string mcq_Choice_2 { get; set; }
        public string mcq_Choice_3 { get; set; }
        public string mcq_Choice_4 { get; set; }
        public string Correct_Answer { get; set; }
        public int ID { get; set; }
    }
}
