//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportsTable
    {
        public string Student_Username { get; set; }
        public string examName { get; set; }
        public System.DateTime date { get; set; }
        public double score { get; set; }
        public double totalscore { get; set; }
        public int ID { get; set; }
        public string status { get; set; }
        public Nullable<double> percentage { get; set; }
    }
}
